### ISSUE TITLE
Disallow any implementation of a Retrofit interface

### ISSUE THREAD

**Issue by gatesn** [palantir/gradle-baseline#1041]
@robert3005

**Comment by robert3005** [comment]
I thought about this more and this is not as bad as I made it to be. I think the weirdness comes from people trying to implement default conjure generated retrofit clients which return retrofit calls. Better fix that's not punishing but instead encourages users to do the right thing is to remove ability to generate those retrofit clients which I started in https://github.com/palantir/conjure-java/pull/641
