### ISSUE TITLE
ErrorProne Check for Log Arg Ordering

### ISSUE THREAD

**Issue by tpetracca** [palantir/gradle-baseline#1053]
## What happened?

I had a log line in my codebase that put arguments *after* the throwable and thus got undesired/broken behavior.
```
Throwable t = ...
log.error("Exception!", t, SafeArg.of("safeArg", arg));
```

## What did you want to happen?

Would have been nice if my code failed to build because it in fact should have been:
```
Throwable t = ...
log.error("Exception!", SafeArg.of("safeArg", arg), t);
```

**Comment by carterkozak** [comment]
#1054
