### ISSUE TITLE
errorProneApply removes suppressed UnusedVariable field

### ISSUE THREAD

**Issue by dansanduleac** [palantir/gradle-baseline#1159]
## What happened?

running `classes -PerrorProneApply` in conjure-python removed this "unused" field which is actually necessary for argument parsing to work as expected.

```java
        @CommandLine.Unmatched
        @SuppressWarnings("UnusedVariable")
        private List<String> unmatchedOptions;
```

## What did you want to happen?

Don't remove fields that are explicitly marked with `@SuppressWarnings("UnusedVariable")`

**Comment by carterkozak** [comment]
i think we should take one more step, and avoid removing fields that are annotated.

**Comment by dansanduleac** [comment]
Like altogether? That might make sense. Is there any way we can make it a suggestion instead for those cases?

**Comment by carterkozak** [comment]
I'm not aware of any way to change the level of a check dynamically
