### ISSUE TITLE
baseline-idea overwrites WORKING_DIRECTORY for all run configurations

### ISSUE THREAD

**Issue by Que3216** [palantir/gradle-baseline#116]
baseline-idea overwrites the WORKING_DIRECTORY for all run configurations: https://github.com/palantir/gradle-baseline/blob/9619a7c3e4045a90ce2ccc077fa7273afcebce3a/gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineIdea.groovy#L166

- Could this behaviour confusing for users? (it took me a while to track the problem down to baseline-idea)
- Is there a way to override the WORKING_DIRECTORY for a run configuration?

**Comment by uschi2000** [comment]
This setting was added to harmonize the behavior between
Gradle/eclipse/idea. What's the use case for making it configurable?

**Comment by Que3216** [comment]
We have multiple configuration folders for running the server (src/dev/var, src/ete/var, src/dist/var etc.). Each folder contains the certificates and config files etc. for that configuration. We then want the default run configuration in idea to use the src/dev WORKING_DIRECTORY, so that it uses the dev configs.

**Comment by uschi2000** [comment]
How do you set this up in Eclipse?

**Comment by Que3216** [comment]
I think we have manually created .launch files

**Comment by uschi2000** [comment]
The base directory behavior in Baseline is chosen to make
Eclipse/Idea/Gradle compatible. It sounds to me that you're forcing
non-standard behavior in Eclipse and Gradle.

**Comment by Que3216** [comment]
For now I've just symlinked the `var` directory, which solves the problem.

**Comment by nemines** [comment]
Having the same problem here and spent a reasonable amount of time debugging before finding this.
I can't see why overwriting custom working directory configuration specified by the user is a feature (removing therefore an IntelliJ feature, what's the point of having a WORKING_DIRECTORY parameter at all, if baseline makes it not configurable?) 
`$MODULE_DIR$` should just be default for newly created configs, not overwrite existing ones.

**Comment by uschi2000** [comment]
This should be fixed by https://github.com/palantir/gradle-baseline/pull/163
