### ISSUE TITLE
Problem on internal project as a result of the save on actions plugin change

### ISSUE THREAD

**Issue by mglazer** [palantir/gradle-baseline#1174]
## What happened?

We started to encounter a problem on one of our internal projects (message me internally for details), which makes it so that any release after this change:

https://github.com/palantir/gradle-baseline/pull/1151

Has prevented builds from running correctly in IntelliJ when we generate the project with `gradlew idea`. Our particular project makes somewhat heavy use of annotation processors, and probably does some other funky things.

The only error I've been able to get from IntelliJ is:

```
Error:java: 	annotations: [org.immutables.value.Generated, java.lang.SuppressWarnings, javax.annotation.ParametersAreNonnullByDefault, javax.annotation.Generated, javax.annotation.concurrent.Immutable, javax.annotation.CheckReturnValue, java.lang.Deprecated, com.fasterxml.jackson.databind.annotation.JsonDeserialize, com.fasterxml.jackson.annotation.JsonAutoDetect, javax.annotation.Nullable, com.fasterxml.jackson.annotation.JsonProperty, com.fasterxml.jackson.annotation.JsonInclude, java.lang.Override, javax.annotation.concurrent.NotThreadSafe, com.google.errorprone.annotations.CanIgnoreReturnValue, java.lang.SafeVarargs, com.fasterxml.jackson.annotation.JsonCreator]
```

Unfortunately, because IntelliJ uses an external compilation process now, even when I turn on debug logging for the build log, I've been unable to capture anything else (but am happy to provide my unredacted build.log if it helps, but I haven't seen anything interesting).

## What did you want to happen?

Compiles to work. I'm currently working on seeing if we can make native gradle integration work, and if that works, this might just not be an issue.

**Comment by mglazer** [comment]
OK, so I spent way too long debugging this, and have found the source of the problem, and it's pretty absurd. So just to give background on the diagnostics, I had to debug the javac process in IntelliJ and then decompile the IntelliJ source and step through the JavaBuilder methods since the exception was being caught deeply in there. Once I got to that step, I found the error was actually here:

```
!line.contains("error") && !line.contains("requires target release")
```

from:

https://github.com/JetBrains/intellij-community/blob/b0185d06db527906a0a2c7fd277972264698e6c7/jps/jps-builders/src/org/jetbrains/jps/incremental/java/JavaBuilder.java#L1189



Because our annotation processors print out the line:

```
	annotations: [org.immutables.value.Generated, java.lang.SuppressWarnings, edu.umd.cs.findbugs.annotations.SuppressFBWarnings, javax.annotation.ParametersAreNonnullByDefault, javax.annotation.Generated, javax.annotation.concurrent.Immutable, javax.annotation.CheckReturnValue, java.lang.Deprecated, com.fasterxml.jackson.databind.annotation.JsonDeserialize, com.fasterxml.jackson.annotation.JsonAutoDetect, javax.annotation.Nullable, com.fasterxml.jackson.annotation.JsonProperty, java.lang.Override, javax.annotation.concurrent.NotThreadSafe, com.google.errorprone.annotations.CanIgnoreReturnValue, com.fasterxml.jackson.annotation.JsonCreator, com.fasterxml.jackson.annotation.JsonTypeInfo, com.fasterxml.jackson.annotation.JsonIgnoreProperties, java.lang.SafeVarargs, com.fasterxml.jackson.annotation.JsonValue]
```

If you look carefully, it's because `com.google.errorprone.annotations.CanIgnoreReturnValue` is registered as an annotation.

This seems to be desired behavior, since we like when Immutables are generated with proper annotations (yay!), however, it fails when IntelliJ just does very simple string searching.

I am able to work around this problem by doing the really funky thing of excluding `-XprintProcessorInfo` from our JVM args:

```
-Xmaxerrs -XprintRounds 
```

And that was just a flag that we had in our custom IntelliJ config. So, not a baseline problem. 

I will probably file a bug against IntelliJ since this is pretty bad.

**Comment by ferozco** [comment]
Thanks for the explanation @mglazer! since this isn't an issue with baseline per se i'm going to close this out

**Comment by mglazer** [comment]
If anyone ever wants to know how to debug the compilation process in IntelliJ, this blog entry was very helpful:

https://medium.com/@joachim.beckers/debugging-an-annotation-processor-using-intellij-idea-in-2018-cde72758b78a#70e8
