### ISSUE TITLE
Running :baseline-error-prone:test OOMs

### ISSUE THREAD

**Issue by AlexLandau** [palantir/gradle-baseline#1182]
When I clone the repo on my MacBook Pro and try to `./gradlew build`, I get consistent errors in the `:baseline-error-prone:test` task with `Aborting due to java.lang.OutOfMemoryError: Java heap space`. This typically happens about 20 seconds into the task.

This looks related to the fact that it's trying to run 16 tests in parallel in a single process, according to the Gradle output. The process appears to max out around 800-900 MB RAM in Activity Monitor and the hprof is around 600 MB.

I was able to work around this by adding the following to the baseline-error-prone/build.gradle:

```
tasks.withType(Test) {
    // Use doFirst so this doesn't get overwritten by the baseline-testing plugin
    doFirst {
        systemProperty("junit.jupiter.execution.parallel.enabled", "false");
    }
}
```

**Comment by carterkozak** [comment]
I think we've been overzealous with parallel annotations in our test error-prone tests, we can get rid of those given how computationally expensive it is to run each test.
