### ISSUE TITLE
FR: warn on Optional.flatMap(v -> Optional.ofNullable(fn(v)))

### ISSUE THREAD

**Issue by markelliot** [palantir/gradle-baseline#1326]
## What happened?
`Optional#map` coerces nulls to empty, so it's redundant to say `Optional.flatMap(v -> Optional.ofNullable(fn(v)))`.

## What did you want to happen?
Errorprone should tell me to write `Optional.map(fn)`.

**Comment by carterkozak** [comment]
I like it, great idea
