### ISSUE TITLE
Findbugs' Removal

### ISSUE THREAD

**Issue by derenrich** [palantir/gradle-baseline#152]
I assume the recommendation here is to replace findbugs with error-prone? There was zero discussion here and the release doesn't mention anything other than saying findbugs is no longer supported. The README used to discuss the change but now it no longer does.

Also, can we add findbugs back? We are introducing a backcompat break for lots of people here for little gain. People likely have customized sets of findbug rulesets that they don't want to part with.

**Comment by iamdanfox** [comment]
FindBugs is no longer maintained (although there is a new thing called [spotbugs](https://github.com/spotbugs/spotbugs)).  I think most users of `com.baseline.error-prone` have been happy with it's static analysis.

Could you file a dedicated issue for any checks which you miss after moving from findbugs -> error-prone?

Will endeavour to communicate these deprecations & changes better next time!
