### ISSUE TITLE
RegexpSinglelineJava breaks when you have `()` in your explanation

### ISSUE THREAD

**Issue by ellisjoe** [palantir/gradle-baseline#154]
I get checkstyle errors for something of the form
```
// TODO(jellis): foo.bar()
```

**Comment by uschi2000** [comment]
My regex isn't specific enough. Want to go fix it?

**Comment by gsheasby** [comment]
+1, @gbonik ran into this yesterday.

**Comment by iamdanfox** [comment]
Fixed by https://github.com/palantir/gradle-baseline/pull/266
