### ISSUE TITLE
Check for logger names: log not logger

### ISSUE THREAD

**Issue by ash211** [palantir/gradle-baseline#159]
Opinion from https://github.com/palantir/http-remoting/pull/404#discussion_r111818846 :

Bad:

```
private static final Logger logger = LoggerFactory.getLogger(Http2Agent.class);
```

Good:

```
private static final Logger log = LoggerFactory.getLogger(Http2Agent.class);
```

**Comment by NeilRickards** [comment]
On a related note, a lot of projects get the case wrong: `private static final Logger LOGGER`
Loggers are not constants.  In a lot of cases they're not even immutable.

**Comment by uschi2000** [comment]
If you want to push this through, can you please open a thread on our internal Baseline mailing list?

**Comment by qinfchen** [comment]
@ash211, it is not clear to why `log` is better than `logger`. Can you elaborate?

**Comment by uschi2000** [comment]
it's not better or worse, it's about picking one.

**Comment by uschi2000** [comment]
and it seems that `log` is used more frequently than `logger`. (although this is a claim without data.)

**Comment by qinfchen** [comment]
got it. +1 on picking one style.
