### ISSUE TITLE
Check for Preconditions.checkArgument using String interpolation

### ISSUE THREAD

**Issue by ash211** [palantir/gradle-baseline#160]
gradle-baseline 0.11.1 does not catch this, maybe newer versions do

Bad:

```
Preconditions.checkArgument(collection.size() >= threshold,
  "Collections size needs to be at least " + threshold);
Preconditions.checkArgument(collection.size() >= threshold,
  String.format("Collections size needs to be at least %d", threshold));
```

Good:

```
Preconditions.checkArgument(collection.size() >= threshold,
  "Collections size needs to be at least %s", threshold);
```

Don't want to do excessive String concatenations via either `+` or `String.format`, especially for tight loops.

**Comment by ash211** [comment]
Same with `Validate.isTrue`

**Comment by schlosna** [comment]
nit: might want to do validation checks on message format strings as well -- e.g. Guava Preconditions only support `%s` placeholder, commons-lang supports `String.format`

**Comment by markelliot** [comment]
I think errorprone will catch the formatter string thing but not necessarily the constant string. Should be straight forward to add if it doesn't.

On Apr 19, 2017, at 12:55 PM, David Schlosnagle <notifications@github.com<mailto:notifications@github.com>> wrote:


nit: might want to do validation checks on message format strings as well -- e.g. Guava Preconditions only support %s placeholder, commons-lang supports String.format
