### ISSUE TITLE
Enforce casing and naming of slf4j static `Logger` field

### ISSUE THREAD

**Issue by iamdanfox** [palantir/gradle-baseline#1642]
## What happened?

Our tooling currently allows people to name their logger fields anything they want (and also tolerates different capitalizations):
```java
private static final Logger log = LoggerFactory.getLogger(MyClass.class);
private static final Logger LOG = LoggerFactory.getLogger(MyClass.class);
private static final Logger LOGGER = LoggerFactory.getLogger(MyClass.class);
private static final Logger logger = LoggerFactory.getLogger(MyClass.class);
```

I've observed a couple of code-review nit threads where the one of these has been picked and the maintainers would prefer another.

## What did you want to happen?

I'd like tooling to just enforce this (and ideally auto-fix everywhere), because I don't think it's a valuable thing for authors/reviewers to spend time on and reduces the signal to noise ratio of code reviews. My preferred variant would be:

```java
private static final Logger log = LoggerFactory.getLogger(MyClass.class);
```

**Comment by carterkozak** [comment]
+1 for standardization here. I wrote a similar one-off errorprone-based fix for https://github.com/apache/httpcomponents-client/pull/236
