### ISSUE TITLE
Bring in gradle-launch-config-plugin for eclipse/idea

### ISSUE THREAD

**Issue by ash211** [palantir/gradle-baseline#168]
https://github.com/palantir/gradle-launch-config-plugin

**Comment by uschi2000** [comment]
Not convinced this should be part of standard Baseline. The vast majority of projects doesn't need launch config, and for those that do I don't quite see the advantage of making it part of Baseline versus applying it separately. Maybe I'm missing something, Andrew?

**Comment by ash211** [comment]
Ah you're right -- I see these paired together so often at first glance it seems like they should go together, but given non-launch java projects like libraries this shouldn't be a part of standard baseline.
