### ISSUE TITLE
Add error prone check to validate name of SafeArg is a constant

### ISSUE THREAD

**Issue by mnazbro** [palantir/gradle-baseline#173]
With the introduction of the [Safe Logging API](https://github.com/palantir/safe-logging), we should be using the same logic as the SLF4J message check to guarantee safety in the messages you are logging.

**Comment by mnazbro** [comment]
@gracew

**Comment by markelliot** [comment]
Humans that use `SafeArg` are explicitly documenting the content as safe, while this would be the most cautious approach it doesn't seem very high priority.

**Comment by iamdanfox** [comment]
Closing out as we haven't had further requests for this in >1 year.
