### ISSUE TITLE
ValidateConstantMessage check is buggy

### ISSUE THREAD

**Issue by darora** [palantir/gradle-baseline#176]
Haven't played around with error prone too much, but from the looks of it we might need to split out the method on Validate.* based on the number of params they take before the error message. The current implementation (afaict) looks for the last string arg and takes that to be the pattern message.

An easy way to cause the current implementation to fail is using a string variable as the value to be interpolated into the error string. e.g. https://github.com/palantir/gradle-baseline/compare/develop...darora:develop

**Comment by darora** [comment]
@ash211 to correct me if I overlooked something

**Comment by gracew** [comment]
related: #175

**Comment by iamdanfox** [comment]
Closing out stale issue
