### ISSUE TITLE
error-prone rule to disallow `{}` in log statements

### ISSUE THREAD

**Issue by gracew** [palantir/gradle-baseline#182]
plus potentially other validation:
- SafeArg/UnsafeArg cannot use the same name
- SafeArg/UnsafeArg cannot use names parseable as non-negative integers

**Comment by uschi2000** [comment]
Hmm, this might be a pretty hard sell for general baseline?

**Comment by gracew** [comment]
yes, that's fair. we could make it a rule in our internal logging library, but I'm concerned about the additional configuration that projects will have to make:
```
dependencies {
    errorprone "com.palantir.sls.logging:sls-logging-error-prone"
}
```

**Comment by uschi2000** [comment]
I don't know a good solution, I'm afraid.

**Comment by ash211** [comment]
Can error-prone branch on package name?  Could make this slf4j-style prohibition only apply to classes under the `com.palantir` package.

Here's what I wrote up earlier about what we might want to check in error-prone:

- safe/unsafe parameters don't have name overloads
  - e.g. `log.info("value1 was {} and value2 was {}", SafeArg("value", 1), UnsafeArg("value", 1));`
- same as above but within same safety of params (both are safe, or both are unsafe)
- no slf4j substitution patterns `{}` get written out by sls-logging for Palantir products
  - e.g. `log.info("value1 was {} and {}", SafeArg("value", 1));` has an extra `{}`
- safe/unsafe parameters aren't named values that are parseable
  - e.g. `SafeArg("1", "asdf")` should be disallowed in some way

**Comment by uschi2000** [comment]
Yes, it can.

**Comment by gracew** [comment]
don't think this is really necessary anymore with the addition of #211

**Comment by markelliot** [comment]
I think we may want this to apply when safe-logging stuff is on the classpath, and not otherwise.

**Comment by jmcampanini** [comment]
i believe @scottsj ran into issues when trying to conditionally check based on the presence of safe-logging. i want to say you can do it by doing the detection at the gradle-baseline level - and not even adding this specific rule to the errorprone classpath if baseline doesn't see the safe-logging.

**Comment by markelliot** [comment]
can we just play the same game as in #211?

**Comment by jmcampanini** [comment]
i believe they:

> (3) Use WARNING instead of ERROR

**Comment by markelliot** [comment]
Can you tune warnings to behave as errors? In which case we can have baseline customize the control generally to apply it as an error and have consumers that don’t want the control can easily turn it off/back to a warning?

**Comment by scottsj** [comment]
Yeah so in #211 we made this a warning, and provided an example to show how to turn it OFF/ERROR in `build.gradle`: https://github.com/palantir/gradle-baseline#error-prone-suppressions

It would be easy to add code in `build.gradle` to disable/enable the error depending if the package is in the classpath - but is there an easy way to ship with this?
