### ISSUE TITLE
Error-prone ignore generated?

### ISSUE THREAD

**Issue by henryptung** [palantir/gradle-baseline#191]
See https://github.com/google/error-prone/issues/463.

This seems like a suitable thing to add to `baseline-error-prone`, at least by the history of a similar fix to the Findbugs code previously.

**Comment by qinfchen** [comment]
It is documented in the [README](https://github.com/palantir/gradle-baseline#error-prone). 

+1 since majority of the projects have generated files and we are already suppressing checkstyle on generated files.

**Comment by iamdanfox** [comment]
Fixed here: https://github.com/palantir/gradle-baseline/pull/298/files#diff-3985771af72397a4b2d1556616eacde9R37
