### ISSUE TITLE
make dependencies.baseline default to same version of configuration files 

### ISSUE THREAD

**Issue by qinfchen** [palantir/gradle-baseline#193]
Currently, it is required to specify the baseline configuration files in dependencies block. Can we make it default to the same version of configuration files if it is not being set? The benefit is simplifying the config block since it is fairly common that we use the same version for the plugin and configuration file. 

```
dependencies {
    // Adds a dependency on the Baseline configuration files. Typically use 
    // the same version as the plugin itself.
    baseline "com.palantir.baseline:gradle-baseline-java-config:<version>@zip"
}
```

**Comment by uschi2000** [comment]
We separated it to make it obvious how to use a separate/different
configuration.

**Comment by qinfchen** [comment]
It makes sense to separate them and provide a way to use a different configuration. I think we can also provide a good default that minimizes the config block and using the same version of configuration and plugin is a pretty common use case.

**Comment by uschi2000** [comment]
The default was removed in order to make the configuration space more
democratic and not favour a single configuration. Feel free to start a
thread on our mailing list to see if people would want to revert this
behaviour.

**Comment by qinfchen** [comment]
cool. is there link to the pr?

**Comment by uschi2000** [comment]
https://github.com/palantir/gradle-baseline/pull/135
