### ISSUE TITLE
Consider delegating Java formatting to google-java-format

### ISSUE THREAD

**Issue by uschi2000** [palantir/gradle-baseline#194]
https://github.com/google/google-java-format/

**Comment by uschi2000** [comment]
@jmcampanini FYI, in case you're interested in doing stuff in baseline. this would be my next target here.

**Comment by a10y** [comment]
@uschi2000 Another alternative is https://github.com/diffplug/spotless/tree/master/plugin-gradle. Doesn't lock us into Google Style Guide (not sure how much we diverge from it) but downside is that unlike google-java-format there's no corresponding IntelliJ plugin.
