### ISSUE TITLE
Design for extension is absurd for test methods

### ISSUE THREAD

**Issue by iamdanfox** [palantir/gradle-baseline#198]
> Method 'smoke_test' is not designed for extension - needs to be abstract, final or empty.

![screen shot 2017-07-14 at 14 58 36](https://user-images.githubusercontent.com/3473798/28215179-f8890032-68a4-11e7-9db5-2b8fe0db9ffc.png)

I appreciate this is very minor, but it is a paper-cut that will encourage people to either: not write tests or disable checkstyle.  I can't see any upside.

**Comment by markelliot** [comment]
Just mark the test class as final?

**Comment by iamdanfox** [comment]
I appreciate that's a way of making this red cross going away, but can you help me understand the usefulness of this check?  Especially if someone is on the brink of disabling checkstyle, I'm concerned that this is one of the checks with a high annoyance : usefulness value that might make people just disable checkstyle.

**Comment by uschi2000** [comment]
Happy to disable it for src/test/java. Want to make a PR?

**Comment by robert3005** [comment]
DFE already ignores anything with `@Test`, `@Before`, `@BeforeClass`, `@After` and `@AfterClass` - this looks like a bug in eclipse checkstyle
