### ISSUE TITLE
URL link for custom error prone patterns

### ISSUE THREAD

**Issue by NeilRickards** [palantir/gradle-baseline#200]
Our custom patterns such as `PreconditionsConstantMessage` currently give a non-existent link (`http://errorprone.info/bugpattern/PreconditionsConstantMessage`).  They should override `linkUrl()` to point to somewhere that exists.

**Comment by iamdanfox** [comment]
Verified this is solved now. (Example with baseline 0.30.0):

```
        log.info("Creating a new TaggedMetricRegistry for {} {}",
                ^
    (see https://github.com/palantir/gradle-baseline#baseline-error-prone-checks)
error: warnings found and -Werror specified
1 error
1 warning

FAILURE: Build failed with an exception.
```
