### ISSUE TITLE
Disallow multiple empty lines

### ISSUE THREAD

**Issue by cihati** [palantir/gradle-baseline#203]
Google Java style guide says it's permitted, thought never suggested/encouraged: https://google.github.io/styleguide/javaguide.html#s4.6.1-vertical-whitespace

I believe we should disallow in all cases. Since it might be controversial, I'm creating an issue and pasting how I achieved in my project.

I've managed to do by applying the following snippet into my checkstyle.xml:

```
        <module name="EmptyLineSeparator"> <!-- Java Style Guide: Source file structure -->
            <property name="tokens" value="IMPORT, CLASS_DEF, ENUM_DEF, INTERFACE_DEF, CTOR_DEF, STATIC_INIT, INSTANCE_INIT, VARIABLE_DEF, METHOD_DEF"/>
            <property name="allowNoEmptyLineBetweenFields" value="true"/>
            <property name="allowMultipleEmptyLines" value="false"/>
            <property name="allowMultipleEmptyLinesInsideClassMembers" value="false"/>
        </module>
```

**Comment by uschi2000** [comment]
Can Eclipse and IntelliJ be configured to honour this behaviour?

**Comment by cihati** [comment]
Apparently possible in IntelliJ: https://stackoverflow.com/questions/11118204/how-to-remove-unnecessary-blank-line-on-code-formatting-in-intellij (don't know eclipse)

**Comment by iamdanfox** [comment]
Fixed by https://github.com/palantir/gradle-baseline/pull/259
