### ISSUE TITLE
checkstyle.xml rules don't work with checkstyle 8.1

### ISSUE THREAD

**Issue by justinuang** [palantir/gradle-baseline#207]
I get this with the latest version of intellij 2017.2

```
2:51 PM	The Checkstyle rules file could not be parsed.
				SuppressionCommentFilter is not allowed as a child in Checker
				The file has been blacklisted for 60s.
```

As per http://checkstyle.sourceforge.net/releasenotes.html, we need to move the filter under TreeWalker, but that breaks compatibility with checkstyle 7.5.1, which is the default now.

**Comment by justinuang** [comment]
Workaround in Idea is to force the version of checkstyle in the settings.

**Comment by uschi2000** [comment]
See https://github.com/palantir/gradle-baseline/pull/205

**Comment by umeshsulakude** [comment]
Even i had the same error but work when i matched the checkstyles versions.

**Comment by iamdanfox** [comment]
Rob is moving the `SuppressionCommentFilter` in #313
