### ISSUE TITLE
It seems gradle-baseline 0.16.0 is not compatible with pre-4.0 version of Gradle

### ISSUE THREAD

**Issue by gslonim-zz** [palantir/gradle-baseline#209]
When we bumped baseline version to 0.16.0, our gradle builds immediately started breaking with `> Cannot set the value of read-only property 'configDir' for object of type com.palantir.baseline.plugins.BaselineCheckstyle.` 

We did not dig too deep into it, but upgrading Gradle to 4.0 immediately solves this problem. Perhaps you could reflect this compatibility/requirement in the README

**Comment by uschi2000** [comment]
The release indicate the 4.0 requirement.

Sent from Email+ secured by MobileIron

-------- Original Message --------

**Comment by gslonim-zz** [comment]
Sorry, Rob, you are correct. Readme still lists 3.3.0+ though.

**Comment by uschi2000** [comment]
Cheers. Fixed on develop./
