### ISSUE TITLE
Baseline should validate jqwik implementation is present when the runner is used

### ISSUE THREAD

**Issue by carterkozak** [palantir/gradle-baseline#2098]
## What happened?

See https://github.com/palantir/tritium/pull/1371

## What did you want to happen?

The build should fail and tell me that jqwik tests aren't executed

**Comment by schlosna** [comment]
Looks like we could easily add this to https://github.com/palantir/gradle-baseline/blob/develop/gradle-baseline-java/src/main/groovy/com/palantir/baseline/tasks/CheckJUnitDependencies.java
