### ISSUE TITLE
Inconsistent Java warnings between Eclipse and IntelliJ

### ISSUE THREAD

**Issue by jtibshirani** [palantir/gradle-baseline#23]
Using the baseline settings, I noticed a few small differences between Eclipse and IntelliJ in terms of what warnings are reported for Java. In particular, Eclipse warns about the use of raw types and missing serialVersionUID, while IntelliJ doesn't. I'm using IntelliJ IDEA 15, Community Edition.

Thanks!

**Comment by iamdanfox** [comment]
Closing out stale issue.
