### ISSUE TITLE
Confusing attempted safety check with XX_PREVIEW

### ISSUE THREAD

**Issue by j-baker** [palantir/gradle-baseline#2340]
## What happened?

Using the PRs @iamdanfox wrote, I configured my JDK to use preview versions:

```gradle
javaVersions {
  libraryTarget = '19_PREVIEW'
  distributionTarget = '19_PREVIEW'
  runtime = '19_PREVIEW'
}
```

This failed with error:

```
> Cannot cast object '19_PREVIEW' with class 'java.lang.String' to class 'int'
```

After much gnashing of teeth (including figuring out if I was even using the right version of Baseline) I discovered that while distributionTarget and runtime support receiving strings, libraryTarget does not, and requires an int.

This was extremely confusing to me. I think that if it's desired that libraryTarget not be allowed to publish with preview versions (it makes sense), it should accept the string and give a more pleasant error message. 

## What did you want to happen?

Consistency. Let me write:

```
javaVersions {
  libraryTarget = '19'
  distributionTarget = '19_PREVIEW'
  runtime = '19_PREVIEW'
}
```

and if I do mess up and write '19_PREVIEW' then error with

```
> Preview features cannot be enabled on library projects. This is because it transitively requires all consumers to enable preview features, and given these are subject to change in backwards-breaking ways, this makes published libraries extremely brittle.
> Offending declaration: libraryTarget = '19_PREVIEW'
```

and not a cast exception.

**Comment by iamdanfox** [comment]
:+1: Amusingly I _almost_ implemented exactly this functionality in the original PR... agreed it seems like a common point of confusion.
