### ISSUE TITLE
IDE should warn if method is missing @Override

### ISSUE THREAD

**Issue by jtibshirani** [palantir/gradle-baseline#24]
Baseline's Java guidelines suggest you should always use the `@Override` annotation. To help enforce this, the default settings for Eclipse and IntelliJ should issue a warning for missing `@Override` annotations.

**Comment by uschi2000** [comment]
Julie, do you know a good way for enabling such a check in IDE/IntelliJ/Gradle builds?

**Comment by jtibshirani** [comment]
In IntelliJ, you can enable the warning by going to Preferences -> Editor -> Inspections, then setting 'Missing `@Override` Annotation' to 'warning'. These can then be exported as xml (Manage -> Export in the same tab), and copied into the IntelliJ project's settings file. I'd guess the settings can be updated + exported similarly in Eclipse.

**Comment by bdworth** [comment]
I'm pretty sure Baseline's default Eclipse settings already warn for this. Unfortunately, I don't think there's a way to have missing @Overrides fail builds.

**Comment by nmiyake** [comment]
Opened #47 as PR to fix this issue. Currently, neither Eclipse nor IDEA has this configured as a warning. It's not as noticeable in Eclipse since it's configured to auto-add the annotation if it's missing, but if you open a previously saved file you can verify that previously it did not warn about this.

**Comment by nmiyake** [comment]
@jtibshirani @uschi2000 fix for this has merged so issue can be marked as fixed

**Comment by uschi2000** [comment]
Thanks a lot, Nick!

**Comment by jtibshirani** [comment]
Thanks @nmiyake !
