### ISSUE TITLE
SafeLoggingPropagation generates spotless format violations

### ISSUE THREAD

**Issue by lycarter** [palantir/gradle-baseline#2453]
## What happened?

![image](https://user-images.githubusercontent.com/10535774/202232274-a40db3d6-bf95-4ad8-91ae-7d475542dd4a.png)

## What did you want to happen?

![image](https://user-images.githubusercontent.com/10535774/202232385-0eb70e4c-cf77-415b-88f4-d9f49d1f52e4.png)

Adding the annotations from SafeLoggingPropagation should put them on a new line, rather than doubling up annotations on a single line (eg, for `@Value.Immutable`)

**Comment by carterkozak** [comment]
@lycarter No error-prone checks write formatted code, our automation runs the java formatter after diffs are applied. Gradle flakes on builds can prevent the formatter from executing successfully, I would check the run logs to understand why that occurred.
