### ISSUE TITLE
Support gradle 8

### ISSUE THREAD

**Issue by robert3005** [palantir/gradle-baseline#2499]
## What happened?

Currently running this plugin on gradle 8 fails for couple of reasons:
1. If you use junit jupiter and haven't set useJUnitPlatform() yourself the plugin will want to do it at runtime which fails now
2. Java toolchains configuration have been revamped and will need adjusting. At the moment all you get is
```
class com.palantir.baseline.plugins.javaversions.BaselineJavaCompiler cannot be cast to class org.gradle.jvm.toolchain.internal.DefaultToolchainJavaCompiler (com.palantir.baseline.plugins.javaversions.BaselineJavaCompiler is in unnamed module of loader org.gradle.internal.classloader.VisitableURLClassLoader @4bae9068; org.gradle.jvm.toolchain.internal.DefaultToolchainJavaCompiler is in unnamed module of loader org.gradle.initialization.MixInLegacyTypesClassLoader @28975c28)
```

I think this is caused by toolchain changes made in 8, 7.6 works fine
3. There's an issue with gradle-versions but that lives in another repo 

## What did you want to happen?

Project should build without errors

**Comment by JochenGuckSnk** [comment]
The lack of gradle 8 support blocks also other plugins... 
[#618](https://github.com/palantir/gradle-docker/issues/618)
