### ISSUE TITLE
gradle-baseline recommends "Save Actions" plugin which is incompatible with IntelliJ 2023.1

### ISSUE THREAD

**Issue by ash211** [palantir/gradle-baseline#2545]
## What happened?

- gradle-baseline recommends "Save Actions" plugin [here](https://github.com/palantir/gradle-baseline/blob/144edb46c54bcef01825942de8f81edacff7a1b3/gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineIdea.groovy#L599-L610)
- that plugin is incompatible with the latest version of IntelliJ: https://github.com/dubreuia/intellij-plugin-save-actions/issues/427
- the way this fails is that you can't save files in window panes

As a result, I lost a whole screen full of written code as a result :(

## What did you want to happen?

We should stop suggesting the "Save Actions" plugin, and instead move to IntelliJ's native "Actions on Save" functionality, assuming that meets our needs.  I think just code formatting and optimizing imports.

**Comment by ash211** [comment]
An alternative is to move to this fork, since the original plugin is now un-maintained: https://github.com/dubreuia/intellij-plugin-save-actions/issues/427#issuecomment-1488812298

**Comment by CRogers** [comment]
This is being fixed. Please do not use the fork by some random person.
