### ISSUE TITLE
Only run error-prone on CI as an explicitly named task

### ISSUE THREAD

**Issue by iamdanfox** [palantir/gradle-baseline#258]
Devs compile code locally hundreds of times a day and it appears that running error-prone on every single one of these compilations leads to quite a significant slowdown.  @j-baker observed a 2 minute build dropping to 40 seconds when error-prone was disabled.

Also, any team that parallelises their CI across multiple containers (or circle2 jobs) will end up wastefully running error-prone more than once.

## Proposal

We could make a new task called `compileJavaErrorProne` which is a dependency of `check`.  All the normal `compileJava` invocations could then run without error-prone locally.  

Error-prone seems pretty [easy to configure](https://github.com/tbroyer/gradle-errorprone-plugin/blob/b9435711d4202a107c393dea5f8e0b8272f25bde/src/main/java/net/ltgt/gradle/errorprone/ErrorPronePlugin.java#L20), so I'm confident we could find something good here!

**Comment by markelliot** [comment]
it's surprising there's such a slowdown, have we investigated why it's slowing things down instead of disabling it?

**Comment by markelliot** [comment]
the other thing to do here is that it runs as a plugin in Java 9, so would be easier to manipulate if/how it runs:
http://errorprone.info/docs/installation

**Comment by j-baker** [comment]
Looking at the traces, the extra time is distributed pretty evenly across the various compilation stages.

**Comment by robert3005** [comment]
Apparently https://github.com/tbroyer/gradle-errorprone-javacplugin-plugin (it applies to jvm via Xplugin) also works with java 8 so we could switch to that which then deals with most of the issues in the current plugin though still has some slowdown over vanilla compilation.

**Comment by robert3005** [comment]
Is this still a problem after changes in 0.32.0 and later? My very unscientific tests on some local codebases showed at most 50% slowdown

**Comment by iamdanfox** [comment]
Happy to close out as I think switching to use the error-prone-javac plugin improved perf significantly.  I hope it'll be sufficient to convince people to stop doing the `-PenableErrorProne=true` thing!
