### ISSUE TITLE
Readme.md - usage section description error

### ISSUE THREAD

**Issue by atai** [palantir/gradle-baseline#2597]
## What happened?

This part of the documentation does not work.

![image](https://github.com/palantir/gradle-baseline/assets/1330201/f93d352e-2d65-4426-974e-2ba8a797feee)

After applying this snippet to the root build.gradle file I got an error:

> Unable to load class 'org.gradle.api.plugins.quality.FindBugs'.
> 
> This is an unexpected error. Please file a bug containing the idea.log file.

I guess the 'version' should be 5.13.0 - the current plugin version.
## What did you want to happen?

What is the right snippet to activate the plugin?

**Comment by fawind** [comment]
Yes, `<version>` is used as an example placeholder here and meant to be replaced with the latest version of gradle-baseline. You can get the latest version from the release page here: https://github.com/palantir/gradle-baseline/releases.

For example, to use version `5.13.0` of gradle-baseline, you would write:

```gradle
buildscript {
    // ...

    dependencies {
        classpath 'com.palantir.baseline:gradle-baseline-java:5.13.0'
    }
}
```

I'll mark this as closed for now, but let us know if that doesn't help!
