### ISSUE TITLE
[IllegalSafeLoggingArgument] Propagate log safety to records

### ISSUE THREAD

**Issue by ash211** [palantir/gradle-baseline#2676]
## What happened?

Consider an unsafe record member of another record:
```
@Unsafe
public record InnerRecord(String description) {}

public record OuterRecord(List<InnerRecord> innerRecords) {}
```

## What did you want to happen?

This should require that an `@Unsafe` annotation is added to `OuterRecord`, but it currently does not seem required.

fyi @carterkozak

**Comment by carterkozak** [comment]
https://github.com/palantir/gradle-baseline/pull/2700
