### ISSUE TITLE
do not require copying a .baseline directory

### ISSUE THREAD

**Issue by bavardage** [palantir/gradle-baseline#27]
could be cool to only put overrides in there? then (assuming no tweaks) upgrading is just a matter of bumping the gradle module version

**Comment by uschi2000** [comment]
Would love to do that, but it's unfortunately pretty complicated since a lot of the config is nested XML. Do you have an idea?

**Comment by markelliot** [comment]
Java can easily render resources from within the jars...it seems like the thing to do here would be to use the resources with a selection criteria: first check to see if .baseline/<resource> exists, then look inside the jar as a fallback. This means for default configurations that you get the right behavior.
