### ISSUE TITLE
Checkstyle should ignore generated_src by default

### ISSUE THREAD

**Issue by bavardage** [palantir/gradle-baseline#28]
I'm getting a bunch of errors about immutables indentation

**Comment by bavardage** [comment]
adding &lt;filter name="DerivedFiles" enabled="true"/&gt; to .checkstyle.xml fixes this in eclipse, but I see this commit https://github.com/palantir/gradle-baseline/commit/2d035543d819133406d44be63294dd36ec68e687 does the same thing?

how about a release w/ this functionality?

**Comment by uschi2000** [comment]
making a release now

**Comment by uschi2000** [comment]
release 0.2.3 should now be available
