### ISSUE TITLE
Bump Java libraryTarget from 11 -> 17

### ISSUE THREAD

**Issue by ash211** [palantir/gradle-baseline#2930]
## What happened?
We're currently compiling gradle-baseline against Java 11: [source](https://github.com/palantir/gradle-baseline/blob/2f78d05879f988ee4a3669b854e392f5ce35b33e/build.gradle#L70)

One of our dependencies, Google error-prone, is compiling against Java 17: [source](https://github.com/google/error-prone/blob/db6c890a54835e5ea618b73b79bbe362d6051d3f/pom.xml#L185-L186)

Most of our internal repos are in the process of moving from Java 17 to Java 21.

error-prone uses a lot of JDK internal code that doesn't have as strong compatibility guarantees between JDK versions, and I think this is related to a large number of exceptions I'm seeing: `java.lang.Error` from `com.sun.source.util.TreePath$1Result.<init>` in `TreePath.java:67` (running with 17)

![Screenshot 2024-10-25 at 11 44 22 AM](https://github.com/user-attachments/assets/1e78e276-bcee-407f-9d0a-a9b34664948f)

## What did you want to happen?
Fewer errors thrown from this codepath while running gradle commands.

I'm not completely sure that bumping this Java version would reduce these errors, but it seems unlikely to hurt.  The bigger challenge to raising the floor here is getting all prereqs bumped first.

**Comment by ash211** [comment]
Would be fixed by https://github.com/palantir/gradle-baseline/pull/2898

**Comment by CRogers** [comment]
Should hopefully be fixed now with version 6.0.0?

**Comment by ash211** [comment]
Hmm no better unfortunately, so it must be something else.  Maybe these exceptions are just expected in the SafeLoggingPropagation, ErrorProne, and JDK 17/21 all interact?

![Screenshot 2024-11-04 at 3 37 49 PM](https://github.com/user-attachments/assets/7c143592-ad20-4977-b501-657fc45108c8)

**Comment by CRogers** [comment]
Is the project this is going wrong in compiling with a Java 11 JDK? ie is `javaVersion(s)` set to `11`? Because that would explain it.
