### ISSUE TITLE
Check class uniqueness escape hatches

### ISSUE THREAD

**Issue by raiju** [palantir/gradle-baseline#294]
Can we add escape hatches to disable the checks for certain sub-classpaths?

There are certain classpaths that are apparently very popular to repackage (e.g. `javax.inject`) that can't always be meaningfully excluded. At that point we get to a place where the choices are all quite bad:
 - Try to convince the dependency (sometimes it's a few transitive layers down) to remove that extra class & rebuild the package chain
 - Not pull in the dependency (not really feasible, I'm actually trying to use that code)
 - Disable the uniqueness check plugin (the most likely option to be chosen)

**Comment by iamdanfox** [comment]
@raiju currently, I use [gradle dependency substitution](https://docs.gradle.org/current/userguide/customizing_dependency_resolution_behavior.html#sec:module_substitution) to make the easy ones go away:

```gradle
    configurations.all {
        resolutionStrategy.eachDependency { DependencyResolveDetails details ->
            if (details.requested.group == 'org.glassfish.hk2.external' && details.requested.name == 'javax.inject') {
                details.useTarget group: 'javax.inject', name: 'javax.inject', version: '1'
                details.because "The glassfish shaded copy is only necessary for OSGI environments, which we do not endorse."
            }
        }
    }
```

What are the specific instances that you'd like to ignore?

**Comment by iamdanfox** [comment]
Revisiting this, I think an escape hatch might actually make sense as I've found a false positive between old http-remoting and new conjure-java-runtime.  I know these classes are exactly the same as we just copied and [pasted them](https://github.com/palantir/conjure-java-runtime/blob/develop/conjure-java-jaxrs-client/src/main/java/feign/TextDelegateEncoder.java).

```
4 Identically named classes with differing impls found in [com.palantir.remoting3:jaxrs-clients:3.44.3, com.palantir.conjure.java.runtime:conjure-java-jaxrs-client:4.2.1]: [feign.TextDelegateEncoder, feign.CborDelegateEncoder, feign.TextDelegateDecoder, feign.CborDelegateDecoder]
```

**Comment by carterkozak** [comment]
Fixed the above issue here: https://github.com/palantir/conjure-java-runtime/pull/900

**Comment by carterkozak** [comment]
Thoughts on re-enabling this check by default? https://github.com/palantir/gradle-baseline/pull/482

**Comment by iamdanfox** [comment]
My big concerns is that I really don't want to block people's uptake of core baseline - let's roll it out to the highline templates again and maybe excavate it to a few repos?

**Comment by carterkozak** [comment]
https://github.com/palantir/conjure-java-runtime/pull/901
https://github.com/palantir/conjure-java-runtime-api/pull/166

**Comment by iamdanfox** [comment]
Closing out because the new baseline-class-uniqueness.lock approach lets you see what the current state of the world is, without _requiring_ you to pass everything.
