### ISSUE TITLE
Issue with JDK22 multi-version JARs

### ISSUE THREAD

**Issue by Fokko** [palantir/gradle-baseline#2967]
## What happened?

It looks like either the shadow plugin or the baseline checker doesn't handle the JDK22 files well. There are also Java version specific files for JDK 17 and 21, which are handled correctly:

```
> baseline-class-uniqueness detected multiple jars containing identically named classes. Please resolve these problems, or run `./gradlew checkClassUniqueness --fix`to accept them:
  
   # Danger! Multiple jars contain identically named classes. This may cause different behaviour depending on classpath ordering.
  # Run ./gradlew checkClassUniqueness --fix to update this file
  
  ## runtimeClasspath
  [com.fasterxml.jackson.core:jackson-core, org.apache.parquet:parquet-jackson]
    - META-INF.versions.22.com.fasterxml.jackson.core.internal.shaded.fdp.v2_18_1.FastDoubleSwar
    - META-INF.versions.22.com.fasterxml.jackson.core.internal.shaded.fdp.v2_18_1.FastIntegerMath
```

## What did you want to happen?

To pass the check without having to fix the duplicates.

**Comment by carterkozak** [comment]
This sounds like a parquet-jackson issue, I don't see `22` listed here: https://github.com/apache/parquet-java/blob/586a35442208941bd45835b96db62f06ac7edd39/parquet-jackson/pom.xml#L95-L119

The other versions are relocated correctly, but those classes are recorded into the same location that they exist in the original jackson module.

**Comment by Fokko** [comment]
Good catch @carterkozak, I missed that one. Sorry for the noise.

**Comment by carterkozak** [comment]
No worries :-)
