### ISSUE TITLE
Make Java compiler warnings for equality checks ERROR by default

### ISSUE THREAD

**Issue by mnazbro** [palantir/gradle-baseline#297]
Error prone provides a bunch of checks via warnings and errors. Given that most warnings are ignored, by making these errors, users would be able to improve their code quality.

**Comment by iamdanfox** [comment]
@mnazbro wanna open a PR to add the `-Werror` thing to https://github.com/palantir/gradle-baseline/blob/develop/gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineErrorProne.groovy#L25 ?

**Comment by mnazbro** [comment]
@raiju You were interested in an escape hatch in case there were warnings outside of your control. I've outlined how the escape hatch should work in the relevant PR.
