### ISSUE TITLE
./gradlew cleanEclipse leaves the .settings directory

### ISSUE THREAD

**Issue by szunami** [palantir/gradle-baseline#30]
I would expect that the following sequence would leave my project in its original state:

./gradlew eclipse
./gradlew cleanEclipse

Yet, the .settings directory is created by the eclipse task and not deleted by cleanEclipse.

**Comment by jmcampanini** [comment]
@sszuflita if you don't apply the baseline eclipse plugin, and you run `eclipse` then `cleanEclipse`, is the `/.settings` directory still there?

rephrased: does this mean that the baseline eclipse plugin changes the default behavior?

**Comment by szunami** [comment]
@jmcampanini the vanilla eclipse plugin leaves the .settings directory too.

**Comment by jmcampanini** [comment]
hrm. then i'd be inclined to think that we should leave it there, since we're not necessarily changing the expectations of `cleanEclipse`.

is that fair?

**Comment by uschi2000** [comment]
+1

**Comment by szunami** [comment]
After a bit more investigation, the cleanEclipse task (in both the eclipse and baseline-eclipse plugins) leaves the .settings directory but removes any files that were added by the eclipse task. This makes some sense; you might have added some files to the .settings directory which you don't want cleanEclipse to delete blindly.

This seems correct; closing this issue.

**Comment by szunami** [comment]
Just kidding.
The baseline-eclipse cleanEclipse task leaves several files in the .settings directory, namely:

edu.umd.cs.findbugs.core.prefs
edu.umd.cs.findbugs.plugin.eclipse.prefs
org.eclipse.jdt.ui.prefs

The normal cleanEclipse task removes any files added to this directory by the eclipse task. This seems like a bug. Sorry for the back and forth.

**Comment by jmcampanini** [comment]
oh interesting, if it makes files and that's why the directory is still present, then yea, that feels like a bug.

in either case, these should be gitignored, right?

just to make sure i understand, the vanilla eclipse plugin leaves the `.settings/` folder but leaves it empty?

**Comment by szunami** [comment]
Yes; vanilla eclipse leaves the .settings folder empty while the baseline-eclipse leaves those files in the .settings.

**Comment by iamdanfox** [comment]
Closing out as there's been no movement on this issue in the last 2 years.  Internally, most teams are pushing to just use intellij everywhere now.
