### ISSUE TITLE
Should the gradle idea task generate immutables?

### ISSUE THREAD

**Issue by szunami** [palantir/gradle-baseline#31]
In order to generated immutable classes (or other annotation based classes), a user has to make their project within their ide. Should the idea task address this?

**Comment by uschi2000** [comment]
At first glance: I don't think so. Why would you expect this behaviour?

**Comment by szunami** [comment]
I guess I would expect ./gradlew idea to fully prepare a project for development in Intellij.

Currently, running ./gradlew idea creates the .iml, .ipr, and .iws files, but doesn't autogenerate annotation based classes. As a result, a user who runs ./gradlew idea and then opens their project in Intellij will get "Cannot resolve ____" for all of the autogenerated code. This is reasonable, and Intellij's "make project" generates the classes.

But I think that opening a project with missing code, I wouldn't expect using "make" to fix anything.

**Comment by uschi2000** [comment]
I can see the intent, but I don't think we should go down this route. Seems like trying to call into IntelliJ to run some compilation is going to be a massive hack.
