### ISSUE TITLE
Palantir copyright headers?

### ISSUE THREAD

**Issue by szunami** [palantir/gradle-baseline#32]
Why are there Palantir copyright headers in:
https://github.com/palantir/gradle-baseline/blob/develop/gradle-baseline-java-config/resources/eclipse/static/dotfile.settings/org.eclipse.jdt.ui.prefs

If they belong here, they should be updated to 2016.

**Comment by uschi2000** [comment]
https://github.com/palantir/gradle-baseline/pull/33
