### ISSUE TITLE
Checkstyle does not seem to understand do-while blocks and always rejects them

### ISSUE THREAD

**Issue by zakmagnus** [palantir/gradle-baseline#341]
If I have a do-while block, checkstyle gives an error like this on the line with the right curly:
`error: '}' at column 9 should be on the same line as the next part of a multi-block statement.`
whether or not my `while` is on the same line as the curly. So, I don't understand what it wants. Regardless of style, it seems impossible to have a do-while loop.

I know there was https://github.com/palantir/gradle-baseline/pull/132 to fix something around this issue. Frankly, I don't understand how that's even supposed to work, since checkstyle docs seem to say that `RightCurly` with `option=same` doesn't apply to do-while loops anyway, it applies to if/else and try/catch. Are the docs wrong? I know this change was copied from google so I guess it should be trustworthy.

Anyway, it doesn't work.

**Comment by zakmagnus** [comment]
Don't close this. In fact, I just hit this the other day. Please fix @iamdanfox

**Comment by iamdanfox** [comment]
@zakmagnus I actually just tried this with latest baseline 0.37.4 and passed the following code just fine:

```java
int i = 0;
do {
    i++;
} while (Math.random() < 0.5d);
```

Reading https://github.com/checkstyle/checkstyle/issues/3320, it seems like Checkstyle fixed this issue upstream.  Are you still able to reproduce this problem on a vanilla repo on latest baseline?

**Comment by zakmagnus** [comment]
I agree with your results. It works on baseline 0.37.4. Thanks!
