### ISSUE TITLE
Question: when should we tag baseline 1.0.0

### ISSUE THREAD

**Issue by iamdanfox** [palantir/gradle-baseline#362]
Baseline just released 0.32.0, which will likely make people's compileJava tasks fail as a result of errorprone suppression syntax changes (https://github.com/palantir/gradle-baseline/pull/354).

https://semver.org/#how-do-i-know-when-to-release-100

> If your software is being used in production, it should probably already be 1.0.0. If you have a stable API on which users have come to depend, you should be 1.0.0. If you’re worrying a lot about backwards compatibility, you should probably already be 1.0.0.

Given that baseline is already widely used inside Palantir and we do care about backwards compatibility, I think we should tag 1.0.0 soon.  We should also probably define what will warrant a major release (e.g. stricter checkstyle rules probably shouldn't be a major rev).

**Comment by iamdanfox** [comment]
I think we need to keep this open because we're now on 0.38.0. I think it might be sufficient to say any changes which will cause a previously working build to fail at configuration time are major breaks. (e.g. requiring a higher minimum gradle version).

@robert3005 any other criteria you'd like to pin to a 1.0?

**Comment by robert3005** [comment]
Don't think we need to add anything more - not sure if you get anything out of major versions since we always force users to latest.

**Comment by iamdanfox** [comment]
I propose we tag 1.0 when gradle-baseline requires gradle 5.0.  Then it should be very clear for users what versions they can upgrade to

**Comment by carterkozak** [comment]
Resolved by https://github.com/palantir/gradle-baseline/releases/tag/1.0.0
