### ISSUE TITLE
Gradle 4.9 Requirement

### ISSUE THREAD

**Issue by daberkow** [palantir/gradle-baseline#367]
Hi!
I just wanted to leave a note, after version 0.30 you need gradle 4.9 or when running "baselineUpdateConfig" youll get `> org.gradle.api.tasks.TaskContainer.register(Ljava/lang/String;Lorg/gradle/api/Action;)Lorg/gradle/api/tasks/TaskProvider;`

**Comment by iamdanfox** [comment]
I think we might even have a 4.10 requirement elsewhere - will update the README to make sure this is captured.

In your specific project, is upgrading your gradle wrapper feasible? (Excavator should be opening gradle upgrade PRs?)

**Comment by daberkow** [comment]
I was able to update gradle, not a problem, I just wanted to alert you so no one else got caught up. :)
