### ISSUE TITLE
Doesn't work with Eclipse out of the box

### ISSUE THREAD

**Issue by fmance** [palantir/gradle-baseline#385]
Applying the `com.palantir.baseline` plugin to the root project and applying the `java` plugin to the subprojects causes the generated eclipse `.project` file to have the `CheckstyleBuilder` before the `javabuilder`

```
	<buildSpec>
		<buildCommand>
			<name>net.sf.eclipsecs.core.CheckstyleBuilder</name>
			<arguments/>
		</buildCommand>
		<buildCommand>
			<name>org.eclipse.jdt.core.javabuilder</name>
			<arguments/>
		</buildCommand>
	</buildSpec>
```

This makes Eclipse unhappy: `The project cannot be checked by Checkstyle because the Checkstyle Builder is set to run before the Java Builder`

The (non-ideal) workaround is to apply each sub-plugin individually, and only apply the `baseline-checkstyle` plugin on `subprojects` after applying the `java` plugin

**Comment by fmance** [comment]
cc @iamdanfox

**Comment by iamdanfox** [comment]
Fixed by https://github.com/palantir/gradle-baseline/pull/484
