### ISSUE TITLE
Idea default copyright contains apache2 headers, eclipse does not

### ISSUE THREAD

**Issue by j-baker** [palantir/gradle-baseline#40]
Not sure which one you want to standardise on, but they're currently out of sync.

https://github.com/palantir/gradle-baseline/blob/develop/gradle-baseline-java-config/resources/eclipse/static/dotfile.settings/org.eclipse.jdt.ui.prefs

https://github.com/palantir/gradle-baseline/blob/develop/gradle-baseline-java-config/resources/copyright/apache-2.0.txt

**Comment by uschi2000** [comment]
Ack. Don't have time to fix this in the following 1-2 weeks, but will take a look afterwards.

**Comment by uschi2000** [comment]
(Also happy to look at a PR.)

**Comment by ash211** [comment]
@uschi2000 was this fixed through the most recent series of three merged PRs, starting with #113 ?

**Comment by uschi2000** [comment]
Fixed.
