### ISSUE TITLE
Publish to the gradle plugins portal

### ISSUE THREAD

**Issue by szunami** [palantir/gradle-baseline#41]

**Comment by nmiyake** [comment]
Pretty sure this is already done -- https://plugins.gradle.org/plugin/com.palantir.baseline, https://plugins.gradle.org/search?term=com.palantir.baseline.

**Comment by uschi2000** [comment]
Except they don't work due to classpath issues. (At least last time I
tried.)

**Comment by iamdanfox** [comment]
Closing out - if there are ongoing problems with using the `plugins { id 'com.palantir.baseline' }` syntax, I think it's worth filing a dedicated issue with a good repro and stack trace.
