### ISSUE TITLE
Baseline should ignore generated code

### ISSUE THREAD

**Issue by bavardage** [palantir/gradle-baseline#424]
https://github.com/palantir/gradle-baseline/blob/develop/gradle-baseline-java/src/main/groovy/com/palantir/baseline/plugins/BaselineFormat.java#L40 ends up being problematic for generated code (e.g. via antlr) - it's unlikely generated code will be baseline compliant.

cc @robert3005

**Comment by ellisjoe** [comment]
https://github.com/palantir/gradle-baseline/pull/428
