### ISSUE TITLE
checkVersionsProps should ensure all direct dependencies have an explicit version number

### ISSUE THREAD

**Issue by iamdanfox** [palantir/gradle-baseline#437]
## What happened

I had a build.gradle like this:

```gradle
dependencies {
    compile 'com.google.guava:guava'
    compile 'io.dropwizard:dropwizard-core'
}
```

And a versions.props:

```properties
io.dropwizard:* = 1.2.4
```

And all the tasks passed.

## What should have happened

I think the task actually should reject this repo state and require users to explicitly pick a version for anything they are directly declaring dependencies on.  This will minimise unrelated version changes when other dependencies are upgraded/downgraded.

**Comment by robert3005** [comment]
Disagree - that’s what boms are for? I don’t want to specify a version if there’s a recommendation

**Comment by iamdanfox** [comment]
Ok if a version comes from a BOM, then that should be allowed.  The case I don't want to allow is when you get a version _only_ from a transitive dependency (e.g. in the scenario I describe above)
