### ISSUE TITLE
checkNoUnusedPin fails when overlapping pins refer to different projects

### ISSUE THREAD

**Issue by alxhill** [palantir/gradle-baseline#468]
This fails, wanting to remove the different-repository dependency (which it fails to build without, as the two projects are versioned separately).
```
com.company.product:product-different-repository-api* = 0.17.2
com.company.product:product* = 8.135.0
```

This succeeds, despite resolving to the same dependencies:
```
com.company.product:product* = 8.135.0
com.company.product:product-something-else-api* = 0.17.2
```

Not sure if this is user error or genuinely unexpected but wanted to file for awareness.

**Comment by iamdanfox** [comment]
I'd like to close this out as we recommend all projects use https://github.com/palantir/gradle-consistent-versions instead of com.palantir.baseline-versions now.
