### ISSUE TITLE
SwitchStatementDefaultCase clashes with MissingCasesInEnumSwitch

### ISSUE THREAD

**Issue by markelliot** [palantir/gradle-baseline#499]
## What happened?

Removed default from switch statement per SwitchStatementDefaultCase, now receive MissingCasesInEnumSwitch instead.

## What did you want to happen?

Revert/disable SwitchStatementDefaultCase or otherwise make it smarter.

**Comment by a-k-g** [comment]
I tried to repro this, but couldn't. Maybe there was some enum value actually missing in the switch..case?

**Comment by a-k-g** [comment]
or maybe a bug in error-prone that has since been fixed?
