### ISSUE TITLE
Error message improvement: Clarify correct Preconditions formatting

### ISSUE THREAD

**Issue by AlexLandau** [palantir/gradle-baseline#518]
The error message for GuavaPreconditionsMessageFormat suggests that one should "use printf-style formatting" in Preconditions.check* methods when an argument is passed to the message.

Actually, the Preconditions methods use a somewhat different substitution method from String.format, printf, and friends. It only accepts `%s` as a pattern to be substituted, rather than `%d` and `%.3f` and so on.

There might be some better phrasing here suggesting the use of `%s` specifically rather than just describing it as "printf-style".

Related: https://errorprone.info/bugpattern/PreconditionsInvalidPlaceholder

**Comment by iamdanfox** [comment]
I think we want to focus energy on getting people to use safe-logging Preconditions instead of guava ones.
