### ISSUE TITLE
idea task doesn't handle compileOnly configuration

### ISSUE THREAD

**Issue by ash211** [palantir/gradle-baseline#56]
I had to grab this little snippet from @pwoody to get this working on an internal project

`build.gradle`:

```
idea {
    module {
        scopes.PROVIDED.plus += [ configurations.compileOnly ]
    }
}
```

What's the right way to fix this here in the baseline level vs in every project using the new compileOnly configuration?

**Comment by pwoody** [comment]
I think that gradle 2.12 + intellij 16 should be able to handle this by default, but i honestly haven't seen it work...

**Comment by uschi2000** [comment]
Yeah, I think we can add that.
