### ISSUE TITLE
Deprecate copyright header handling, use license plugin instead

### ISSUE THREAD

**Issue by uschi2000** [palantir/gradle-baseline#59]
https://github.com/hierynomus/license-gradle-plugin
- Remove checkstyle check for Palantir header
- Remove IntelliJ configuration through .baseline/copyright
- If required, add IDE functionality to https://github.com/hierynomus/license-gradle-plugin

**Comment by jmcampanini** [comment]
is there matching eclipse functionality to add the copyright to new files?

**Comment by uschi2000** [comment]
No

**Comment by uschi2000** [comment]
Actually, not quite true. There is, but it's hardcoded rather than being
read through .baseline/copyright
