### ISSUE TITLE
Allow empty lambdas to not have whitespace

### ISSUE THREAD

**Issue by mccheah** [palantir/gradle-baseline#615]
## What happened?

The following code produces an error in checkstyle:
```
args.forEach(arg -> {});
```

Checkstyle will complain and ask for this:

```
args.forEach(arg -> { });
```
## What did you want to happen?

It seems reasonable for empty lambdas to not have any whitespace. This is similar to empty method bodies in private constructors, for example.

**Comment by schlosna** [comment]
@mccheah do you have a more realistic example? It feels like any no-op like this (`forEach`, `Runnable`) etc. is a bit odd as you’re just burning CPU cycles.

**Comment by carterkozak** [comment]
This comes to mind, though it doesn't come up frequently: https://github.com/palantir/tracing-java/blob/develop/tracing/src/main/java/com/palantir/tracing/Tracer.java#L268

**Comment by mccheah** [comment]
The issue linked above in Iceberg shows where we're concerned: https://github.com/apache/incubator-iceberg/pull/153#discussion_r276761560

**Comment by iamdanfox** [comment]
Fixed here https://github.com/palantir/gradle-baseline/pull/715

baseline 1.8.0
