### ISSUE TITLE
Disallow AuthHeader and BearerToken from being passed to logging functions

### ISSUE THREAD

**Issue by dsd987** [palantir/gradle-baseline#650]
## What happened?
Objects containing sensitive authentication information like AuthHeader and BearerToken can be accidentally passed to logging functions like slf4j logging calls or as arguments to other log functions (Preconditions, Validate, etc).

## What did you want to happen?
A error-prone check would mark obviously incorrect logging behavior involving AuthHeader and BearerToken objects as invalid.

**Comment by dsd987** [comment]
Quickly implemented #654 as a potential solution to cover slf4j and safe/unsafe args.

**Comment by carterkozak** [comment]
#654 has merged.
