### ISSUE TITLE
FR: help users avoid Duration#getNanos/toNanos foot gun

### ISSUE THREAD

**Issue by iamdanfox** [palantir/gradle-baseline#657]
## What happened?

I just wrote some silly code:

```java
future.get(duration.getNanos(), TimeUnit.NANOSECONDS);
```

## What did you want to happen?

I intended to write:

```java
future.get(duration.toNanos(), TimeUnit.NANOSECONDS);
```

**Comment by gatesn** [comment]
https://errorprone.info/bugpattern/ProtoDurationGetSecondsGetNano

**Comment by carterkozak** [comment]
This should already be covered by [JavaDurationGetSecondsGetNano](https://errorprone.info/bugpattern/JavaDurationGetSecondsGetNano) which uses WARNING level by default.
