### ISSUE TITLE
Add a gradle task that will create or update .baseline to the default for current version

### ISSUE THREAD

**Issue by markelliot** [palantir/gradle-baseline#7]

**Comment by uschi2000** [comment]
Let's discuss offline; it's tricky :(

**Comment by uschi2000** [comment]
Unless you're happy with something like this:


def baselineDependency = dependencies.create("com.palantir.baseline:baseline-config:+@zip")
def baselineConfig = configurations.detachedConfiguration(baselineDependency)
task baselineUpdateConfig {
    doLast {
        copy {
            from zipTree(baselineConfig.getSingleFile())
            into '.baseline'
        }
    }
}

**Comment by uschi2000** [comment]
Done in release 0.2.1 via baselineUpdateConfig task
