### ISSUE TITLE
Dangling parentheses check does not handle single-line comments

### ISSUE THREAD

**Issue by dtobin** [palantir/gradle-baseline#703]
## What happened?

The rewrite step introduced by https://github.com/palantir/gradle-baseline/pull/687 does not correctly handle single-line comments

```
  foo // this is a comment
)
```
will be rewritten to 
```
  foo // this is a comment)
```
which no longer compiles.

This also needs to handle the case where the entire line is a comment, i.e.
```
  foo
  // whole line is a comment
)
```
so you probably don't want to move the parenthesis to immediately before the comment
## What did you want to happen?

Probably the simplest solution is to perform no rewrite in this case?

**Comment by dtobin** [comment]
Oh, and another bug; this doesn't handle trailing semicolons before a newline and close paren - i.e. from try-with-resources:
```
try (
   Foo closeable1 = create();
   Foo closeable2 = create();
) {
  ...
}
```
There a reasonable fix to drop the last semicolon, but just heads up on another case where this refactor breaks compile.

**Comment by iamdanfox** [comment]
Closing out because we've delete the dangling parens thing in favour of a code formatter.
