### ISSUE TITLE
CompletableFuture *async methods should require an executor

### ISSUE THREAD

**Issue by carterkozak** [palantir/gradle-baseline#737]
## What happened?
The overload which doesn't take an executor uses the fork join pool. Contention from misbehaving blocking work blocks execution in ways that we don't expect. The fork-join-pool doesn't report metrics we can use to diagnost problems.

## What did you want to happen?
We should require an executor to be passed to all methods which can take one. `supplyAsync`, `runAsync`, `thenRunAsync`, etc. In the unlikely case we do really want to use the fork join pool, we can pass `ForkJoinPool.commonPool()`.

**Comment by iamdanfox** [comment]
Fixed here: https://github.com/palantir/gradle-baseline/pull/740
