### ISSUE TITLE
Check that custom InputStreams implement bulk read

### ISSUE THREAD

**Issue by carterkozak** [palantir/gradle-baseline#748]
## What happened?

A custom `InputStream` implementation only provided `read()`, but not `read(byte[],int,int)`, resulting millions of single-byte read operations rather than a few buffer based operations.

## What did you want to happen?

`InputStream` implementations which implement `read()` must also implement `read(byte[],int, int)`.

I imagine this check could work similarly to http://errorprone.info/bugpattern/EqualsHashCode.

**Comment by schlosna** [comment]
Looks like [InputStreamSlowMultibyteRead](https://errorprone.info/bugpattern/InputStreamSlowMultibyteRead) does exactly this, so probably worth us promoting from WARNING to ERROR in baseline

**Comment by carterkozak** [comment]
PR is up, builds are failing because develop is broken, I've staged a commit to revert the most recent commit to develop as well.
