### ISSUE TITLE
java.lang.NoClassDefFoundError on 0.6.1 with gradle 2.14.1

### ISSUE THREAD

**Issue by lcuthriell-zz** [palantir/gradle-baseline#76]
I get java.lang.NoClassDefFoundError: com/google/common/base/MoreObjects with checkstyleMain

**Comment by robert3005** [comment]
I had hit that on contour from day 0 of baseline. The issue is that checkstyle is using configuration.checkstyle and assuming it has its gradle available. The solution is to avoid overriding checkstyle's guava version.

**Comment by uschi2000** [comment]
Is this still a problem in 0.7.0?

**Comment by robert3005** [comment]
Haven't tried 0.7. Just stopped overriding checkstyles guava, seemed simpler. Just wanted to give context for people in the future since I spent half a day figuring out source of this issue once.
