### ISSUE TITLE
testing against multiple versions of gradle

### ISSUE THREAD

**Issue by jmcampanini** [palantir/gradle-baseline#92]
do we have any plans to test `gradle-baseline` against different versions of gradle?
- in nebula-test, you can set the `gradleVersion` at the spec level.
- in gradle test kit, you should be able to declare the version in particular: `.withGradleVersion("2.7")`

this may be worth considering for this plugin

**Comment by uschi2000** [comment]
Not really too interested, to be honest. Would expect Pepe to upgrade their
Gradle versions frequently enough.

**Comment by jmcampanini** [comment]
coo. closing
