### ISSUE TITLE
Options allowing users to apply different set of baseline rules

### ISSUE THREAD

**Issue by qinfchen** [palantir/gradle-baseline#93]
Currently, default rules are applied and you have to modify the xml files to tweak/remove/add rules. Would it make sense to have different sets of rules categorized by strictness, such `base`, `medium`, and `high`? I don't think one default set of rules can cover all use cases.

**Comment by uschi2000** [comment]
Customization makes sense, but probably not in the form of different
levels. We had tried this initially, but it didn't work well. We could
investigate simpler ways for turning certain things on/off based on one
default config.

**Comment by qinfchen** [comment]
👍, let me know if I can help with anything

**Comment by uschi2000** [comment]
I don't have time at the moment to tackle this; if you would like to see
this feature, feel free to submit a PR.

**Comment by iamdanfox** [comment]
Closing out as we've pushed pretty heavily for one uniform set of checks using using excavator.
