### ISSUE TITLE
Consider Prettier for code formatting

### ISSUE THREAD

**Issue by gm2211** [palantir/gradle-baseline#990]
## What happened?

We've been exploring different ways of enforcing a company-wide style. 
Common code formatting tools generally use rules and heuristics to make existing code conform to a given style.
The problem with that is that, depending on the formatting of the input, it gives rise to interesting edge-cases where the result doesn't look very good.

## What did you want to happen?

I would like for us to look into https://github.com/jhipster/prettier-java, which is a Java plugin for https://prettier.io. 
This tool uses a different approach:

1. It parses the code into an AST
2. It re-writes the code in a consistent format

I've played around with it a bit and so far I haven't seen any formatting fail that really stands out.

Would be nice to explore this - not sure if it's configurable enough for our needs, but we could always fork it.

**Comment by iamdanfox** [comment]
We've actually spent a few weeks making a fork of google-java-format produce a formatting style that looks readable: https://github.com/palantir/palantir-java-format.  Unless there is something that is not achievable with that codebase I don't think we're intending to dive into another approach!

In addition, the google-java-format codebase had _really_ nice support for formatting just specific ranges, which means we can make excavator surgically format the lines it has touched without clobbering an entire codebase.

**Comment by gm2211** [comment]
Yup, I've seen that repo - and I've seen that one of the heuristics did not always result in well-formatted code - feel free not to look into this, I just wanted this to be here for the purposes of discoverability - in case you were not aware of the tool - I think parsing ast and re-writing code is an approach that has the best potential.

**Comment by iamdanfox** [comment]
google-java-format actually bundles the entire compiler for this exact purpose, and then re-scans tokens to make sure comments aren't thrown away.  To be clear, the palantir-java-format repo is still a work in progress, if you have cases which don't look good, please do file an issue!

(Also I don't think we want to impose a requirement of nodejs on java devs, which prettier does require AFAIK)

**Comment by iamdanfox** [comment]
I think prettier has been evaluated and we've invested in https://github.com/palantir/palantir-java-format instead.
